const MARKER = '<!-- doclify-guardrail-comment -->';

/**
 * Build a Markdown PR comment body from doclify output.
 * @param {object} output - Doclify JSON output
 * @param {object} [opts]
 * @param {number} [opts.baseScore] - Base branch score for delta calculation
 * @returns {string} Markdown comment body
 */
function buildPrCommentBody(output, opts = {}) {
  const { baseScore = null } = opts;
  const summary = output.summary;
  const status = summary.status === 'PASS' ? 'PASS' : 'FAIL';
  const statusIcon = status === 'PASS' ? '\u2705' : '\u274C';

  const lines = [
    MARKER,
    '## \uD83D\uDCCA Doclify Quality Report',
    '',
    '| File | Score | Errors | Warnings | Status |',
    '|------|-------|--------|----------|--------|'
  ];

  for (const f of output.files) {
    const fileIcon = f.pass ? '\u2705' : '\u274C';
    const score = f.summary.healthScore != null ? `${f.summary.healthScore}/100` : 'N/A';
    lines.push(`| \`${f.file}\` | ${score} | ${f.summary.errors} | ${f.summary.warnings} | ${fileIcon} |`);
  }

  lines.push('');

  // Overall summary
  const avgScore = summary.avgHealthScore != null ? summary.avgHealthScore : '?';
  let deltaStr = '';
  if (baseScore != null && summary.avgHealthScore != null) {
    const delta = summary.avgHealthScore - baseScore;
    deltaStr = delta > 0 ? ` (+${delta} vs base)` : delta === 0 ? ' (\u00B10 vs base)' : ` (${delta} vs base)`;
  }

  lines.push(`**Overall: ${avgScore}/100${deltaStr} \u2014 ${statusIcon} ${status}**`);
  lines.push('');
  lines.push(`> ${summary.filesScanned} file(s) scanned \u00B7 ${summary.totalErrors} error(s) \u00B7 ${summary.totalWarnings} warning(s) \u00B7 ${summary.elapsed}s`);
  lines.push('');
  lines.push(`<sub>Generated by <a href="https://github.com/Elgabor/doclify-guardrail">doclify-guardrail</a> v${output.version}</sub>`);

  return lines.join('\n');
}

/**
 * Post or update a PR comment with the doclify report.
 * @param {object} octokit - Authenticated Octokit instance
 * @param {object} ctx - GitHub context (owner, repo, prNumber)
 * @param {object} output - Doclify JSON output
 * @param {object} [opts] - Options passed to buildPrCommentBody
 */
async function postPrComment(octokit, ctx, output, opts = {}) {
  const { owner, repo, prNumber } = ctx;
  const body = buildPrCommentBody(output, opts);

  // Find existing comment to update (idempotent)
  const { data: comments } = await octokit.rest.issues.listComments({
    owner,
    repo,
    issue_number: prNumber
  });

  const existing = comments.find(c => c.body && c.body.includes(MARKER));

  if (existing) {
    await octokit.rest.issues.updateComment({
      owner,
      repo,
      comment_id: existing.id,
      body
    });
  } else {
    await octokit.rest.issues.createComment({
      owner,
      repo,
      issue_number: prNumber,
      body
    });
  }
}

export { MARKER, buildPrCommentBody, postPrComment };
