const MARKER = '<!-- doclify-guardrail-comment -->';

/**
 * Build a Markdown PR comment body from doclify output.
 * @param {object} output - Doclify JSON output
 * @param {object} [opts]
 * @param {number} [opts.baseScore] - Base branch score for delta calculation
 * @returns {string} Markdown comment body
 */
function buildPrCommentBody(output, opts = {}) {
  const { baseScore = null } = opts;
  const summary = output.summary;
  const status = summary.status === 'PASS' ? 'PASS' : 'FAIL';
  const statusIcon = status === 'PASS' ? '\u2705' : '\u274C';

  const lines = [
    MARKER,
    '## \uD83D\uDCCA Doclify Quality Report',
    '',
    '| File | Score | Errors | Warnings | Status |',
    '|------|-------|--------|----------|--------|'
  ];

  for (const f of output.files) {
    const fileIcon = f.pass ? '\u2705' : '\u274C';
    const score = f.summary.healthScore != null ? `${f.summary.healthScore}/100` : 'N/A';
    lines.push(`| \`${f.file}\` | ${score} | ${f.summary.errors} | ${f.summary.warnings} | ${fileIcon} |`);
  }

  lines.push('');

  // Overall summary
  const avgScore = summary.avgHealthScore != null ? summary.avgHealthScore : '?';
  let deltaStr = '';
  if (baseScore != null && summary.avgHealthScore != null) {
    const delta = summary.avgHealthScore - baseScore;
    deltaStr = delta > 0 ? ` (+${delta} vs base)` : delta === 0 ? ' (\u00B10 vs base)' : ` (${delta} vs base)`;
  }

  lines.push(`**Overall: ${avgScore}/100${deltaStr} \u2014 ${statusIcon} ${status}**`);
  lines.push('');
  lines.push(`> ${summary.filesScanned} file(s) scanned \u00B7 ${summary.totalErrors} error(s) \u00B7 ${summary.totalWarnings} warning(s) \u00B7 ${summary.elapsed}s`);
  if (output.ai?.drift?.summary) {
    const drift = output.ai.drift.summary;
    const alertsByScope = drift.alertsByScope || {};
    const gatingScope = drift.gatingScope || 'all';
    const scopedAlerts = (output.ai?.drift?.alerts || [])
      .filter((alert) => gatingScope === 'all' || alert.scope === 'unmodified');
    const topHigh = scopedAlerts.filter((alert) => alert.risk === 'high').slice(0, 3);
    lines.push('');
    lines.push(`> Drift Guard \u00B7 ${drift.alerts} alert(s) \u00B7 ${drift.high} high \u00B7 ${drift.medium} medium \u00B7 ${drift.low} low \u00B7 scope ${gatingScope} (${alertsByScope.unmodified || 0} unmodified, ${alertsByScope.modified || 0} modified)`);
    if (topHigh.length > 0) {
      lines.push('');
      lines.push('**Top high alerts (gate scope)**');
      for (const alert of topHigh) {
        const reason = Array.isArray(alert.reasons) && alert.reasons.length > 0
          ? ` - ${alert.reasons[0]}`
          : '';
        lines.push(`- \`${alert.doc}\` (${alert.score}/100, ${alert.scope || 'unmodified'})${reason}`);
      }
    }
  }
  lines.push('');
  lines.push(`<sub>Generated by <a href="https://github.com/Elgabor/doclify-guardrail">doclify-guardrail</a> v${output.version}</sub>`);

  return lines.join('\n');
}

/**
 * Post or update a PR comment with the doclify report.
 * @param {object} octokit - Authenticated Octokit instance
 * @param {object} ctx - GitHub context (owner, repo, prNumber)
 * @param {object} output - Doclify JSON output
 * @param {object} [opts] - Options passed to buildPrCommentBody
 */
async function postPrComment(octokit, ctx, output, opts = {}) {
  const { owner, repo, prNumber } = ctx;
  const body = buildPrCommentBody(output, opts);

  // Find existing comment to update (idempotent)
  const comments = await octokit.paginate(octokit.rest.issues.listComments, {
    owner,
    repo,
    issue_number: prNumber,
    per_page: 100
  });

  const existing = comments.find(c => c.body && c.body.includes(MARKER));

  if (existing) {
    await octokit.rest.issues.updateComment({
      owner,
      repo,
      comment_id: existing.id,
      body
    });
  } else {
    await octokit.rest.issues.createComment({
      owner,
      repo,
      issue_number: prNumber,
      body
    });
  }
}

export { MARKER, buildPrCommentBody, postPrComment };
