import fs from 'node:fs';
import path from 'node:path';

/**
 * Generate a markdown report from scan results and write it to disk.
 * @param {object} output - full output object with files[], summary
 * @param {object} options - { reportPath: string }
 * @returns {string} - resolved path of written report
 */
function generateReport(output, options) {
  const lines = [];
  const now = new Date();
  const dateStr = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')} ${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}`;

  lines.push('# Doclify Guardrail Report');
  lines.push('');
  lines.push(`**Date:** ${dateStr}  `);
  lines.push(`**Files scanned:** ${output.summary.filesScanned}  `);
  lines.push(`**Result:** ${output.summary.status === 'PASS' ? '\u2713 PASS' : `\u2717 ${output.summary.totalErrors} errors, ${output.summary.totalWarnings} warnings`}`);
  if (typeof output.summary.avgHealthScore === 'number') {
    lines.push(`**Avg health score:** ${output.summary.avgHealthScore}/100`);
  }
  if (output.ai?.drift?.summary) {
    const drift = output.ai.drift.summary;
    const alertsByScope = drift.alertsByScope || {};
    lines.push(`**Drift Guard:** ${drift.alerts} alert(s) · ${drift.high} high · ${drift.medium} medium · ${drift.low} low · scope ${drift.gatingScope || 'all'} (${alertsByScope.unmodified || 0} unmodified, ${alertsByScope.modified || 0} modified)`);
  }
  lines.push('');

  // Summary table
  lines.push('## Summary');
  lines.push('');
  lines.push('| File | Status | Errors | Warnings |');
  lines.push('|------|--------|--------|----------|');

  for (const f of output.files) {
    const icon = f.pass ? '\u2713 PASS' : '\u2717 FAIL';
    lines.push(`| ${f.file} | ${icon} | ${f.summary.errors} | ${f.summary.warnings} |`);
  }
  lines.push('');

  // Details per file
  const filesWithFindings = output.files.filter(
    f => f.findings.errors.length > 0 || f.findings.warnings.length > 0
  );

  if (filesWithFindings.length > 0) {
    lines.push('## Details');
    lines.push('');

    for (const f of filesWithFindings) {
      lines.push(`### ${f.file}`);
      lines.push('');

      for (const finding of f.findings.errors) {
        const lineRef = finding.line != null ? `line ${finding.line}` : '';
        lines.push(`- **ERROR** ${lineRef}: ${finding.message}`);
      }
      for (const finding of f.findings.warnings) {
        const lineRef = finding.line != null ? `line ${finding.line}` : '';
        lines.push(`- **WARNING** ${lineRef}: ${finding.message}`);
      }
      lines.push('');
    }
  }

  if (output.ai?.drift?.alerts?.length > 0) {
    const driftSummary = output.ai?.drift?.summary || {};
    const gatingScope = driftSummary.gatingScope || 'all';
    const scopedAlerts = output.ai.drift.alerts
      .filter((alert) => gatingScope === 'all' || alert.scope === 'unmodified');
    const topHigh = scopedAlerts
      .filter((alert) => alert.risk === 'high')
      .slice(0, 3);

    lines.push('## Drift Guard');
    lines.push('');
    lines.push(`Gate scope: \`${gatingScope}\``);
    if (topHigh.length === 0) {
      lines.push('- No `high` alerts in gating scope.');
      lines.push('');
    } else {
      lines.push('');
      for (const alert of topHigh) {
        lines.push(`- **${alert.doc}** (${alert.score}/100 · ${alert.risk.toUpperCase()} · ${alert.scope || 'unmodified'})`);
        if (alert.reasons?.length > 0) {
          lines.push(`  - ${alert.reasons.slice(0, 2).join(' | ')}`);
        }
      }
      lines.push('');
    }
  }

  // File errors
  if (output.fileErrors && output.fileErrors.length > 0) {
    lines.push('## Unreadable Files');
    lines.push('');
    for (const fe of output.fileErrors) {
      lines.push(`- \`${fe.file}\`: ${fe.error}`);
    }
    lines.push('');
  }

  // Footer
  lines.push('---');
  lines.push(`*Generated by Doclify Guardrail v${output.version} in ${output.summary.elapsed}s*`);
  lines.push('');

  const reportContent = lines.join('\n');
  const resolvedPath = path.resolve(options.reportPath);
  fs.writeFileSync(resolvedPath, reportContent, 'utf8');
  return resolvedPath;
}

export { generateReport };
